services:
  nginx:
    image: nginx:1.27
    ports:
      - 80:80
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - front
  api:
    build: ./backend
    environment:
      - STORAGE=mysql
      - MYSQL_HOST=db
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PWD=${MYSQL_PASSWORD}
      - MYSQL_DB=todo
    networks:
      - back
  db:
    image: mysql
    volumes:
      - db-volume:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=todo
    networks:
      - back
volumes:
  db-volume:

networks:
  front:
  back:
