services:
  nginx:
    image: nginx:1.27
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - front # Voor scheiding van frontend verkeer
      - traefik # Voor verbinding met de proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`s143204.devops-ap.be`)"    
      - "traefik.http.routers.nginx.entrypoints=websecure"
      - "traefik.http.routers.nginx.tls=true"
      - "traefik.http.routers.nginx.tls.certresolver=letsencrypt"
      - "traefik.docker.network=traefik"

  api:
    build: ./backend
    environment:
      - STORAGE=mysql
      - MYSQL_HOST=db
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PWD=${MYSQL_PASSWORD}
      - MYSQL_DB=todo
    networks:
      - back 
      - traefik
  db:
    image: mysql
    volumes:
      - db-volume:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=todo
    networks:
      - back

volumes:
  db-volume:

networks:
  traefik:
    external: true
  front:
  back:
