services:
  nginx:
    image: nginx:1.27
    ports:
      - 80:80
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
  api:
    build: ./backend
